
services:
  # ======================
  # API GATEWAY
  # ======================
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth:8001
      - MLFLOW_SERVICE_URL=http://mlflow:5000
      - IMAGE_SERVICE_URL=http://image-storage:8003
    depends_on:
      - auth
      - mlflow
    networks:
      - microservices_network

  # ======================
  # AUTH SERVICE
  # ======================
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    container_name: auth
    depends_on:
      - auth-db
    environment:
      - DATABASE_URL=postgresql+psycopg2://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@auth-db:5432/${AUTH_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "8001:8001"
    networks:
      - microservices_network
        
  # ======================
  # AUTH POSTGRES
  # ======================
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB}
    volumes:
      - authdata:/var/lib/postgresql/data
      - ./services/auth-db/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - microservices_network

  # ======================
  # MLFLOW SERVICE
  # ======================
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.4.0
    container_name: mlflow
    environment:
      - BACKEND_STORE_URI=postgresql+psycopg2://${MLFLOW_DB_USER}:${MLFLOW_DB_PASSWORD}@mlflow-db:5432/${MLFLOW_DB}
      - AWS_ACCESS_KEY_ID=${ARTIFACTS_STORAGE_USER}
      - AWS_SECRET_ACCESS_KEY=${ARTIFACTS_STORAGE_PASSWORD}
      - MLFLOW_S3_ENDPOINT_URL=http://mlflow-s3:9000
      - MLFLOW_ARTIFACT_ROOT=s3://mlflow-artifacts
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5000
    depends_on:
      - mlflow-db
      - mlflow-s3
    ports:
      - "5000:5000"
    networks:
      - microservices_network

  # ======================
  # MLFLOW METADATA DB
  # ======================
  mlflow-db:
    image: postgres:15
    container_name: mlflow-db
    environment:
      - POSTGRES_USER=${MLFLOW_DB_USER}
      - POSTGRES_PASSWORD=${MLFLOW_DB_PASSWORD}
      - POSTGRES_DB=${MLFLOW_DB}
    volumes:
      - mlflowdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - microservices_network

  # ======================
  # MLFLOW MINIO Artifact store
  # ======================
  mlflow-s3:
    image: minio/minio
    container_name: mlflow-s3
    volumes:
      - minio_mlflow_data:/data
    environment:
      - MINIO_ROOT_USER=${ARTIFACTS_STORAGE_USER}
      - MINIO_ROOT_PASSWORD=${ARTIFACTS_STORAGE_PASSWORD}
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - microservices_network

  # ======================
  # MLFLOW MINIO INIT BUCKET
  # ======================
  mlflow-s3-init:
    image: minio/mc:latest
    container_name: mlflow-s3-init
    depends_on:
      - mlflow-s3
    environment:
      - MC_HOST_minio=http://${ARTIFACTS_STORAGE_USER}:${ARTIFACTS_STORAGE_PASSWORD}@mlflow-s3:9000
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc mb --ignore-existing minio/mlflow-artifacts;
      exit 0;
      "
    networks:
      - microservices_network

  # ======================
  # IMAGE STORAGE SERVICE
  # ======================
  image-storage:
    build:
      context: ./services/image-storage
      dockerfile: Dockerfile
    container_name: image-storage
    environment:
      - MINIO_ENDPOINT=image-s3:9000
      - MINIO_ACCESS_KEY=${IMAGE_STORAGE_USER}
      - MINIO_SECRET_KEY=${IMAGE_STORAGE_PASSWORD}
      - MINIO_SECURE=false
      - BUCKET_NAME=user-uploads
    depends_on:
      - image-s3
    ports:
      - "8003:8003"
    networks:
      - microservices_network

  # ======================
  # IMAGE STORAGE MINIO
  # ======================
  image-s3:
    image: minio/minio
    container_name: image-s3
    volumes:
      - minio_image_data:/data
    environment:
      - MINIO_ROOT_USER=${IMAGE_STORAGE_USER}
      - MINIO_ROOT_PASSWORD=${IMAGE_STORAGE_PASSWORD}
    command: server --console-address ":9001" /data
    ports:
      - "9100:9000"
      - "9101:9001"
    networks:
      - microservices_network

  # ======================
  # IMAGE STORAGE BUCKET INIT
  # ======================
  image-s3-init:
    image: minio/mc:latest
    container_name: image-s3-init
    depends_on:
      - image-s3
    environment:
      - MC_HOST_minio=http://${IMAGE_STORAGE_USER}:${IMAGE_STORAGE_PASSWORD}@image-s3:9000
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc mb --ignore-existing minio/user-uploads;
      exit 0;
      "
    networks:
      - microservices_network


  # ======================
  # TRAINING SERVICE
  # ======================
  training:
    build: ./services/training
    depends_on:
      - auth
      - auth-db
      - mlflow-s3
      - mlflow
      - image-storage
    environment:
      - DATABASE_URL=postgresql+psycopg2://${MLFLOW_DB_USER}:${MLFLOW_DB_PASSWORD}@mlflow-db:5432/${MLFLOW_DB}
      - MINIO_ENDPOINT=mlflow-s3:9000
      - MINIO_ACCESS_KEY=${ARTIFACTS_STORAGE_USER}
      - MINIO_SECRET_KEY=${ARTIFACTS_STORAGE_PASSWORD}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    shm_size: 2g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8005:8005"
    networks:
    - microservices_network

volumes:
  authdata:
  mlflowdata:
  minio_mlflow_data:
  minio_image_data:

networks:
  microservices_network:
    driver: bridge